name: Update Repo Description

on:
  push:
    paths:
      - 'DESCRIPTION.md'  # Trigger action when DESCRIPTION.md is updated

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set description from DESCRIPTION.md
        run: |
          DESCRIPTION=$(head -n 3 DESCRIPTION.md | tr '\n' ' ')  # Take the first 3 lines as a single line
          echo "Updating repository description to: '$DESCRIPTION'"
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"description\": \"$DESCRIPTION\"}" \
            https://api.github.com/repos/sachnaror/email_extractor
